### ISSUE TITLE
Is the binho Project dead?

### ISSUE THREAD

**Issue by HikingDev** [binhollc/binho-python-package#15]
The last commit was done over a year ago.
Surprisingly the UART API is not available for the Python package.
The GUI Application unfortunately seem not to support writing of hex data.
Is this expected to be delivered? The adapter was not cheap and I am surprised UART is not available

**Comment by jmg5150** [comment]
Thanks for reaching out about this! Our python module definitely isn't dead -- although it has been a bit quiet lately. Mostly due to stability here, we've been focused on a major revamp of our Mission Control desktop software. To be totally honest, we haven't exposed UART operation through our python module yet because it's not a very popular use-case. You're actually the first to ask for it. There is support for UART using our legacy python wrapper, the details/example of which can be found here: https://support.binho.io/python-libraries/python-wrapper/examples/uart-bridge-with-i2c

We're always eager to improve our library and protocol support, so if you could let us know the ideal UART implementation you're looking for, we can get it added in. For example, are you looking for a simple way to 'burst fire' a hex data file out of UART? Or something more like an interactive shell which is packetized hex data instead of the typical human-readable ASCII? Feel free to let us know here or confidentially via support@binho.io and we'll get on it.

**Comment by HikingDev** [comment]
Thanks for the swift response.
First I tried using Missioncontrol to quickly stimulate an ESP32 via UART. The Data is required in hex, which I was unable to transmit using Missioncontrol. When I checked the Python Library I realized that the UART related code has been commented out. 

However I agree that indeed IC2 and SPI are the main use cases. 
Binho still allows us to easily stimulate our ESP32 via SPI and for UART we now use FT232H.
